version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:lts

    steps:
      - checkout

      # Install pnpm
      - run:
          name: "Install pnpm"
          command: "npm install -g pnpm@latest"

      # Install dependencies
      - run:
          name: "Install dependencies"
          command: "pnpm install --frozen-lockfile"

      # Run all tests
      - run:
          name: "Run tests"
          command: "pnpm test:all"

workflows:
  test-workflow:
    jobs:
      - test
